---
- name: Create the JetBrains licensing server group
  group:
    name: "{{ jb_licensing_server_group }}"
    state: present

- name: Create the Jetbrains licensing server user
  user:
    name: "{{ jb_licensing_server_user }}"
    group: "{{ jb_licensing_server_group }}"
    home: "{{ jb_licensing_server_home }}"
    state: present
    createhome: no

- name: Prepare the directory structure
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ jb_licensing_server_user }}"
    group: "{{ jb_licensing_server_group }}"
    mode: 0755
  with_items:
    - "{{ jb_licensing_server_install_base }}"
    - "{{ jb_licensing_server_home }}"

- name: Download and unarchive the licensing server
  unarchive:
    src: "{{ jb_licensing_server_download_url_base }}/{{ jb_licensing_server_package }}"
    dest: "{{ jb_licensing_server_home }}"
    owner: "{{ jb_licensing_server_user }}"
    group: "{{ jb_licensing_server_group }}"
    copy: no

- name: Symlink logs to regular place
  file:
    src: "{{ jb_licensing_server_home }}/logs"
    dest: /var/log/jetbrains
    state: link
    force: yes