---
- name: Setup license server in systemd
  template:
    src: jetbrains-license-server.service.j2
    dest: /etc/systemd/system/jetbrains-license-server.service
    mode: 0755

- name: Ensure licensing server is up and running
  service:
    name: jetbrains-license-server
    state: started
    enabled: yes